DWAPlannerROS:
  max_vel_x: 0.5
  min_vel_x: -0.5
  max_vel_y: 0.5
  min_vel_y: -0.5
  max_trans_vel: 0.6
  min_trans_vel: -0.6
  max_rot_vel: 0.5

  acc_lim_theta: 1.0
  acc_lim_x: 0.5
  acc_lim_y: 0.5

  yaw_goal_tolerance: 0.05
  xy_goal_tolerance: 0.03
